name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deploy on

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials OIDC login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-for-left-unlocked'
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          ./copy-to-dist.sh
          aws s3 cp dist/ s3://leftunlocked.tanay.tech/ --recursive
